import type { Metadata } from "next";
import "./styles/globals.css";
import LogoutButton from '@/components/LogoutButton';

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {

  return (
    <html lang="en">
      <body className="antialiased">
        <div className="grid grid-cols-12 min-h-screen">
          {/* Header */}
          <header className="col-span-12 bg-blue-800 text-white p-4 shadow-md  flex justify-between items-center">
            <div className="text-2xl font-bold tracking-wide">Logo</div>
            <LogoutButton />

            <div className="relative">
              <input
                type="text"
                placeholder="Search..."
                className="p-2 pl-10 bg-blue-700 text-white rounded-md focus:outline-none focus:ring-2 focus:ring-blue-400 transition-all"
              />
              <svg
                xmlns="http://www.w3.org/2000/svg"
                className="w-5 h-5 absolute left-3 top-1/2 transform -translate-y-1/2 text-white"
                fill="none"
                viewBox="0 0 24 24"
                stroke="currentColor"
              >
                <path
                  strokeLinecap="round"
                  strokeLinejoin="round"
                  strokeWidth="2"
                  d="M21 21l-4.35-4.35m2.25-5.65A7 7 0 1111 4a7 7 0 017 7z"
                />
              </svg>
            </div>
          </header>

          {/* Sidebar */}
          <aside className="col-span-2 bg-white border border-gray-200 shadow-lg p-6">
            <nav>
              <ul className="space-y-4">
                <li>
                  <a
                    href="/Dashboard"
                    className="block text-gray-700 hover:text-blue-600 hover:bg-blue-50 px-4 py-2 rounded-lg transition-all"
                  >
                    Dashboard
                  </a>
                </li>
                <li>
                  <a
                    href="/Appointments"
                    className="block text-gray-700 hover:text-blue-600 hover:bg-blue-50 px-4 py-2 rounded-lg transition-all"
                  >
                    Appointments
                  </a>
                </li>
                <li>
                  <a
                    href="/Patients"
                    className="block text-gray-700 hover:text-blue-600 hover:bg-blue-50
                     px-4 py-2 rounded-lg transition-all "
                  >
                    Patients
                  </a>
                </li>
              </ul>
            </nav>
          </aside>


          {children}

          {/* Footer */}
          <footer className="col-span-12 bg-gray-800 text-white text-center p-4">
            Footer
          </footer>
        </div>
      </body>
    </html>
  );
}
